"""
A tiny in-memory audio store.

Since we synthesize audio server-side but the browser needs a URL to
play it (via an <audio> element), we cache the generated bytes keyed by
a UUID and serve them from GET /api/audio/{audio_id}. Entries expire
after a short TTL to avoid unbounded memory growth.
"""
import time
import uuid
from dataclasses import dataclass
from threading import Lock

_TTL_SECONDS = 300  # 5 minutes is plenty for the client to fetch and play


@dataclass
class AudioEntry:
    data: bytes
    mime_type: str
    created_at: float


class AudioStore:
    def __init__(self) -> None:
        self._store: dict[str, AudioEntry] = {}
        self._lock = Lock()

    def put(self, data: bytes, mime_type: str) -> str:
        self._evict_expired()
        audio_id = uuid.uuid4().hex
        with self._lock:
            self._store[audio_id] = AudioEntry(data=data, mime_type=mime_type, created_at=time.time())
        return audio_id

    def get(self, audio_id: str) -> AudioEntry | None:
        with self._lock:
            return self._store.get(audio_id)

    def _evict_expired(self) -> None:
        now = time.time()
        with self._lock:
            expired = [k for k, v in self._store.items() if now - v.created_at > _TTL_SECONDS]
            for k in expired:
                del self._store[k]


_store_instance: AudioStore | None = None


def get_audio_store() -> AudioStore:
    global _store_instance
    if _store_instance is None:
        _store_instance = AudioStore()
    return _store_instance
